### PR TITLE
merge turnstile-core and related branches into master

### PR DESCRIPTION
**Pull request by stchang**
~~Opening this, but dont merge.~~ Ready to merge!

- [x] I want to redo the merges more cleanly tomorrow. 
- [x] And want to make sure travis tests pass

This pr combines:
- `wilbowma/cur turnstile-core`
- `stchang/cur metantac`
- `stchang/cur generic-type-methods`
- fixes from `stchang/cur popl2020-artifact`

So this includes all the additional work from your `turnstile-core`, as well as everything from `popl2020-artifact` except `define-z3-axiom` (to avoid dependency on rosette).

The tests should now pass with `macrotypes master` so after this merge, users should use `cur master` along with `macrotypes master`

### CODE REVIEW

**Comment by stchang** [comment]
Ready to merge!

**Comment by stchang** [comment]
I decided to leave all the commits bc I realized the fine-grained history is useful. I already did a lot of squashing while developing.

**Comment by wilbowma** [comment]
Okay! I'll press the big red (green) button!

**Comment by stchang** [comment]
fingers crossed

**Comment by wilbowma** [comment]
Okay merged! Does this work with macrotypes/turnstile master now?

**Comment by stchang** [comment]
yup. woohoo!

**Comment by wilbowma** [comment]
Huzzah! Thanks for all the work!

**Pull request merged**
