### PR TITLE
Here's a demo of the tactic idea

### PR DESCRIPTION
**Pull request by jeapostrophe**

### CODE REVIEW

**Comment by wilbowma** [comment]
Very cool. I'm doing compiler correctness until Friday, but will play with this this weekend. Why "ntac"?

**Comment by jeapostrophe** [comment]
new

Feel free to change

On Mon, Jun 20, 2016 at 10:26 PM, William J. Bowman <
notifications@github.com> wrote:

> Very cool. I'm doing compiler correctness until Friday, but will play with
> this this weekend. Why "ntac"?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/wilbowma/cur/pull/46#issuecomment-227323984, or mute
> the thread
> https://github.com/notifications/unsubscribe/AAOM-nQ700PbQXXeoCZ-aZAu-mOUHHnMks5qN0vZgaJpZM4I6GQ_
> .

## 

Jay McCarthy
Associate Professor
PLT @ CS @ UMass Lowell
http://jeapostrophe.github.io

```
       "Wherefore, be not weary in well-doing,
  for ye are laying the foundation of a great work.
```

And out of small things proceedeth that which is great."
                          - D&C 64:33

**Comment by wilbowma** [comment]
Okay, got this version working in the branch "ntac". Partly there was a bug in the reflection API, partly the proof was wrong (`(exact c)` did not work since c does not have type Type, but type (And A B); by-assumption used A), and partly namespace problems because Cur's #lang-ness is a hack.
(to be clear, `(exact c)` mostly didnt work due to the namespace issues)

I'm going to clean it up a bit before merging it into master:
- [x] Split core tactic stuff from individual tactics
- [x] see what we can do about `fill`; maybe generate macros for "fill" tactics.
- [x] hide the namespace issue from user defined tactics
- [x] documentation
- [x] sensible error handling (exceptions, w/ try tactical catching and continuing?)

You mentioned you had a simple proof-general-like thing; will it work with this tactic system?

**Comment by jeapostrophe** [comment]
That all sounds good to me. Regarding the simple PG thing. It is here:

https://github.com/jeapostrophe/prover-mode

It is a super trivial way to send an sexp to a repl and then signal that you have "unsent" them, which would correspond to a rewind in the proof state. It would be very easy to make the `interactive` function accept input like this.

**Comment by wilbowma** [comment]
Okay, finally ready to merge this. @jeapostrophe, since you did the design and initial coding, I've currently listed you as an author in the ntac docs as follows. Do you want an email listed/not want yourself listed at all?

```
3.7 ntac–The New Tactic System
by Jay McCarthy
William J. Bowman <email>
```

**Comment by jeapostrophe** [comment]
Very cool! 

I'll leave it up to you whether you list me, I feel like you did the hard work part of it. Please include my racket-lang email if you do put me.

**Comment by wilbowma** [comment]
Closed by 59b54d8e9c4bd6716c1a2a9a766709fe05095877

**Pull request closed without merging**
