### PR TITLE
add ntac documentation

### PR DESCRIPTION
**Pull request by stchang**
I needed some subsequent commits on master so I rebased.

Ie, my new branch `pr-84` is your `pr-79`, rebased with your `master`, and with my new documentation commits.

This replaces #80 and #83

### CODE REVIEW

**Comment by stchang** [comment]
Should be ready now for review and then merge.

**Comment by wilbowma** [comment]
Great thanks! Sorry for unresponsiveness; been out of town until Thursday.

--

**Comment by wilbowma** [comment]
- [x] Should mention explicitly that that r:-> is that racket contract ->, distinguished from the Cur -> type
- [x] Should credit Stephen in the ntac authors
- [ ] Debug define-theorem in docs; I think the compile time state causes a problem with the sandbox. May not be solvable

**Comment by wilbowma** [comment]
@mpoffald, I'm not seeing any of the errors with `define-theorem` on either 6.12 or 7.0; can you try to reproduce?

**Comment by mpoffald** [comment]
Yeah, although maybe my process is wrong?

I just removed existing Cur packages and then ran `raco pkg install` from inside of cur-lib, and then in cur-doc.

I'm using v6.12.

screen shot 2018-07-31 at 6 27 53 pm

**Comment by wilbowma** [comment]
And you're on pr-84? Tried a clean install of Racket?

Could you post a screenshot? Maybe I'm missing something.

**Comment by wilbowma** [comment]
Oh; that looks like maybe it's not define-theorem's fault, but due to delta reduction.
Rebuilding a clean install of Racket now.

**Comment by wilbowma** [comment]
Cannot reproduce on a second linux machine, v7.0 built clean from source.

**Comment by wilbowma** [comment]
Cannot reproduce on a second linux machine, v7.0 built clean from source.
Did reproduce this on v6.12.

Tempted to call this a Racket bug and say v7.0 is required.

**Comment by mpoffald** [comment]
Yep, works fine for me on v7.0.

**Comment by diakopter** [comment]
if only we had a non-buggy implementation of a programming language

**Comment by stchang** [comment]
Fwiw cur tests before this pr was already failing with everything except v7. Have not investigated though so don't know if this is something new.

**Comment by wilbowma** [comment]
Yeah that was my fault and should be fixed. I added some experiments that were not expected to pass to the test suite.

This is about the docs examples.

--

**Comment by wilbowma** [comment]
Okay, I've made a couple changes in my own version of this branch, which now passes:
https://travis-ci.org/wilbowma/cur/builds/411433724

**Pull request closed without merging**
