### PR TITLE
attempt to fix #134

### LINKED ISSUE #134: define definitions recomputed on every call
I think this is because we implement define with a variable transformer instead of actually expanding to a variable de-reference. It surprised me in my attempt at a staged programming example. This has to do with how we implement normalization; we'd need a way to delta reduce variables at compile-time.
```
#lang cur

(require cur/stdlib/nat)
(require racket/trace)
(require cur/debug/syntax-trace)

(trace-define-syntax run
                     (lambda (stx)
                       (syntax-parse stx
                         [(_ expr)
                          (cur-normalize #'expr)])))

(define one (run (plus 1 0)))
one
```

Should print 
```
> (run '(run (plus 1 0)))
<'(s z)
(s z)
```

But actually
```
> (run '(run (plus 1 0)))
<'(s z)
> (run '(run (plus 1 0)))
<'(s z)
'(s z)
```
and we see `run` executed on every call use of `one`.

### PR DESCRIPTION
**Pull request by stchang**

### CODE REVIEW

**Comment by stchang** [comment]
~some tests still failing~ all tests passing again now

I tried various things but kept running into the modules + stx prop problem.

As a partial solution, I added a second "define" called `define-for-export`.
- The original `define` only expands once and has the behavior you expected.
- `define-for-export` waits until the (every) use site to expand (the old behavior)

I think we can improve the second case with a special require transformer that limits expansion to once per module.

But even though it's only a sort-of solution, I think this pr is worth merging, if only because it already improves test suite performance by ~10%

**Comment by wilbowma** [comment]
I'll merge this, but we really need a way to have lazy semantics for definitions.

**Comment by wilbowma** [comment]
In general, does the normalization-by-expansion force an eager semantics?

**Comment by wilbowma** [comment]
Closed via cfeca9251e510f990b7946cfc2187a2714e44161

**Comment by stchang** [comment]
> In general, does the normalization-by-expansion force an eager semantics?

I think yes, with the current expander.

**Comment by wilbowma** [comment]
Okay. I think this is a fundamental problem we need to address. It's related to our problems with universes as well. I think the right solution, as you suggest, requires a different model of expansion. Might have to look at David et al.'s expander. We might be able to hack around, if we want to stick with Racket's current model.

**Pull request closed without merging**
